import { motion } from "motion/react";
import { ChevronDown } from "lucide-react";
import { useState } from "react";

const faqs = [
  {
    question: "What is the total cost of a 5kW solar system?",
    answer:
      "A typical 5kW on-grid solar system costs around ₹3,00,000. After availing the government subsidy of ₹78,000, your net cost becomes ₹2,22,000. We also offer flexible EMI options with zero down payment through partner banks.",
  },
  {
    question: "How long does it take to install the system?",
    answer:
      "The entire process from application to installation and activation typically takes 15-30 days. This includes government approvals, net metering setup, civil works, and system installation. Our team manages all coordination seamlessly.",
  },
  {
    question: "What warranty is provided?",
    answer:
      "We provide comprehensive warranties: 25-year performance warranty on solar panels, 10-year product warranty on inverters, and lifetime customer support. All components are BIS certified and MNRE approved.",
  },
  {
    question: "Can I earn money from excess solar power?",
    answer:
      "Yes! Through the net metering system, excess power generated by your system feeds back to the grid. You earn credits on your electricity bill for the power supplied, typically generating ₹500-1000+ per month in additional income.",
  },
  {
    question: "What if there's no electricity supply at my location?",
    answer:
      "We offer off-grid solar systems with battery backup, perfect for remote areas or as a backup power solution. These systems provide 24/7 power independence and are ideal for businesses and households without reliable grid supply.",
  },
  {
    question: "Is subsidy available to everyone?",
    answer:
      "Subsidy under Surya Ghar Yojana and PM Kusum Scheme is available for eligible residential and agricultural customers. Our team assists with all documentation and qualification verification at no extra cost.",
  },
  {
    question: "What happens during monsoon or cloudy days?",
    answer:
      "Solar panels continue to generate electricity even on cloudy days, though at reduced capacity. On-grid systems remain connected to the grid for uninterrupted power supply. For complete energy independence, we recommend battery backup systems.",
  },
  {
    question: "Do you provide maintenance support?",
    answer:
      "Yes, preventive maintenance is included in our service package. We provide regular cleaning, monitoring, and technical support to ensure optimal system performance. Our 24/7 customer support team is always available for assistance.",
  },
];

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section id="faq" className="py-16 lg:py-24 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-lg text-gray-600">
              Everything you need to know about our solar solutions
            </p>
          </motion.div>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.05 }}
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full bg-gradient-to-r from-gray-50 to-white hover:from-gray-100 hover:to-gray-50 border-2 border-gray-100 hover:border-[#1E40AF] transition-all duration-300 rounded-xl p-6 text-left group"
              >
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-semibold text-gray-900 group-hover:text-[#1E40AF]">
                    {faq.question}
                  </h3>
                  <motion.div
                    animate={{
                      rotate: openIndex === index ? 180 : 0,
                    }}
                    transition={{ duration: 0.3 }}
                    className="flex-shrink-0 ml-4"
                  >
                    <ChevronDown className="w-6 h-6 text-[#1E40AF]" />
                  </motion.div>
                </div>

                {/* Answer */}
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{
                    opacity: openIndex === index ? 1 : 0,
                    height: openIndex === index ? "auto" : 0,
                  }}
                  transition={{ duration: 0.3 }}
                  className="overflow-hidden"
                >
                  <p className="text-gray-600 mt-4 leading-relaxed">
                    {faq.answer}
                  </p>
                </motion.div>
              </button>
            </motion.div>
          ))}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="mt-16 bg-gradient-to-r from-[#1E40AF] to-[#059669] rounded-2xl p-8 text-center text-white"
        >
          <h3 className="text-2xl font-bold mb-4">Still have questions?</h3>
          <p className="mb-6 text-blue-100">
            Our expert team is ready to help you make the best decision for your
            solar journey.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <a
              href="tel:8985203688"
              className="bg-white text-[#1E40AF] hover:bg-blue-50 px-8 py-3 rounded-xl font-semibold transition-all duration-300 hover:scale-105"
            >
              Call Now: 8985203688
            </a>
            <a
              href="tel:9346554750"
              className="bg-white/20 hover:bg-white/30 border border-white text-white px-8 py-3 rounded-xl font-semibold transition-all duration-300"
            >
              9346554750
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
